project:
  type: website
  output-dir: docs
  
execute:
  cache: true
  freeze: auto

website:
  favicon: images/logo.png
  reader-mode: true
  page-navigation: true
  title: "FIP606"
  navbar:
    pinned: true
    logo: images/logo.png
    border: false
    background: "White"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Fundamentos"
        file: R_codes/aula1.qmd
      - text: "Análise Exploratória"
        file: R_codes/aula4.qmd
      - text: "Análise de Dados"
        menu:
        - text: "Teste T"
          file: R_codes/aula8.qmd
        - text: "Transformação Box Cox"
          file: R_codes/aula18.qmd
        - text: "Anova"
          file: R_codes/aula10.qmd
        - text: "Variável categórica"
          file: R_codes/aula15.qmd
        - text: "Regressão"
          file: R_codes/aula14.qmd
        - text: "Mapas"
          file: R_codes/aula16.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/raphaelfitopatologia
      - icon: instagram
        href: https://www.instagram.com/invites/contact/?i=xk2vhn0e4rad&utm_content=2owlczy
      - icon: github
        menu:
          - text: Código fonte
            url:  https://github.com/rb-rosa
          - text: Reportar um erro
            url:  mailto:rbarboza.rosa@gmail.com
  sidebar:
    - title: "Home"
      contents:
        - href: index.qmd
          text: Bem-vindo
        - href: R_codes/rrstudio.qmd
          text: R e RStudio
        - href: R_codes/perfil.qmd
          text: Perfil
    - title: "Fundamentos"
      contents:
        - href: R_codes/aula1.qmd
          text: Quarto
        - href: R_codes/aula2.qmd
          text: Pacotes
        - href: R_codes/aula3.qmd
          text: Importar dados
    - title: "Análise exploratória" 
      contents:
        - href: R_codes/aula4.qmd
          text: Ggplot2
        - href: R_codes/aula5.qmd
          text: Boxplot
        - href: R_codes/aula6.qmd
          text: Gráficos
        - href: R_codes/aula7.qmd
          text: Transformar dados
    - title: "Teste t"
      contents:
        - text: Teste t
          file: 
        - text: "---"    
        - href: R_codes/aula8.qmd
          text: Para dois grupos
        - href: R_codes/aula9.qmd
          text: Amostras dependentes 
    - title: "Anova"   
      contents:
        - text: ANOVA
          file:
        - text: "---"  
        - href: R_codes/aula10.qmd
          text: 1 Fator
        - href: R_codes/aula11.qmd
          text: 2 ou mais fatores
        - href: R_codes/aula12.qmd
          text: DBC
    - title: "Variável categórica" 
      contents:
        - text: Variável categórica
          file:
        - text: "---"  
        - href: R_codes/aula15.qmd
          text: Chi-squared/Fisher's Test"  
    - title: "Regressão"   
      contents:
        - text: Regressão
          file:
        - text: "---"  
        - href: R_codes/aula14.qmd
          text: Linear de segunda ordem
        - href: R_codes/aula17.qmd
          text: Não linear
        - href: R_codes/aula13.qmd
          text: Linear simples, misto e GLM
    - title: "Mapas"
      contents:
        - href: R_codes/aula16.qmd
          text: Mapas
    - title: "Transformação Box Cox"
      contents:
        - href: R_codes/aula18.qmd
          text: Transformação Box Cox 
  
  page-footer:
    border: true
    left: "Copyright 2023, Raphael B Rosa"
format:
  html:
    theme: 
      light: default
      dark: cyborg
      
    css: styles.css
    toc: true
editor: visual
