---
title: "**Importar dados**"
format: html
editor: visual

execute: 
  freeze: auto
  cache: true
  warning: false
---

Aula 3

## De pacotes

```{r}
cars
cars2 <- cars
speed <- cars2

```

## Dataframe de pacotes

```{r}
library(remotes)
remotes::install_github("emdelponte/r4pde")
library("r4pde")
df <- RustSoybean
df
```

## Do excel

```{r}
library(readxl)
magnesio <- read_excel("dados-diversos.xlsx")
escala1 <- read_excel("dados-diversos.xlsx", "escala")
escala2 <- read_excel("dados-diversos.xlsx", 2)

```

## Tabela com menu

O comando "\| echo: false" colocado dentro do Chunk não mostra o código na saída

```{r}
survey <- read_excel("dados-diversos.xlsx", "survey")
library(DT)
datatable(survey,
          extensions = 'Buttons',
          options = list(
            dom = 'Bfrtip',
            buttons = c('copy', 'excel')
          ))
```

## De CSV

```{r}
library(tidyverse)
magnesio2 <- read.csv("dados-diversos.csv")
magnesio3 <- read_csv("dados-diversos.csv")
```

## De TXT

```{r}
magnesio4 <- read.table("dados-diversos.txt", sep = ',')

```

## Do google sheet

### Link da primeira aba

### Link da segunda aba

### Link da internet

```{r}
library(gsheet)
magnesio5 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1aID5Dh6PlBVCKzU1j7k-WA6zuWQWE2NhtWEgdJtt5iA/edit#gid=921203844")
survey <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1aID5Dh6PlBVCKzU1j7k-WA6zuWQWE2NhtWEgdJtt5iA/edit#gid=366054269")
fusarium <- read_csv("https://raw.githubusercontent.com/emdelponte/epidemiology-R/main/data/fusarium_banana.csv")
```
