---
title: "aula4"
format: html
editor: visual

execute: 
  freeze: auto
  cache: true
  warning: false
---

# Ggplot

## Importar dados

```{r}
library(tidyverse)
mg <- read_csv("dados-diversos.csv")

mg |> 
  ggplot(aes(Irrigation, severity, shape = Irrigation))+
  geom_point(alpha = 0.5)

```

```{r}
mg |> 
# filter(rep == 3) |> 
  ggplot(aes(day, severity, shape = Irrigation))+
  geom_point(alpha = 0.5)+
  geom_line()+
  facet_wrap(~rep)
  

```

```{r}
mg2 <- mg |> 
  select(day, rep, severity) |> 
  group_by(day) |> 
  summarize(sev =  mean(severity))

  mg2 |> 
  ggplot(aes(day, sev*100))+
  geom_point()+
  geom_line()+
  ylim(0,100)+
    labs(x = "Time (days)", y = "Severity (%)")
#   Configurar o gráfico
```

```{r}
mg2 |> 
  ggplot(aes(day, sev*100))+
  geom_line(color = "darkorange")+
  geom_point(size = 3, 
             color = "darkorange")+
  scale_x_continuous(breaks = c(0,7,14,21,28,35,42,49,56,63))+
  scale_y_continuous(n.breaks = 5, 
                     limits = c(0,100))+
    labs(x = "Time (days)", 
         y = "Severity (%)", 
         title = "My first ggplot", 
         subtitle = "It is beatiful", 
         caption = "Source: FIP 606")+
#   Configurar o gráfico
  theme_light()
ggsave("figs/myfirstggplot.png",
       bg = "white",
       width = 4,
       height = 3)
```
